networks:
  web_net:
    name: web_net
    external: true
  app_net:
    name: app_net
    external: true

volumes:
  minio_data:
    name: minio_data
    external: false

services:
  minio:
    image: minio/minio:${image_tag}
    container_name: minio
    hostname: minio
    restart: ${restart_policy}
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"  # For connecting to Minio API
      - "9001:9001"  # For viewing Minio Web Console
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${minio_root_user}
      MINIO_ROOT_PASSWORD: ${minio_root_pass}
      MINIO_SERVER_URL: ${minio_api_domain}
      MINIO_BROWSER_REDIRECT_URL: ${minio_console_domain}
    networks:
      - web_net
      - app_net