networks:
  web_net:
    name: web_net
    external: true
  app_net:
    name: app_net
    external: true

volumes:
  nexus_data:
    name: nexus_data
    external: false

services:
  nexus:
    image: sonatype/nexus3:${image_tag}
    container_name: nexus
    hostname: nexus
    restart: ${restart_policy}
    volumes:
      - nexus_data:/nexus-data
    networks:
      - web_net
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-repo.rule=Host(`${nexus_main_domain}`)"
      - "traefik.http.routers.http-repo.entrypoints=web"
      - "traefik.http.routers.repo.rule=Host(`${nexus_main_domain}`)"
      - "traefik.http.routers.repo.entrypoints=web-secure"
      - "traefik.http.routers.repo.tls=true"
      - "traefik.http.routers.repo.tls.certresolver=myresolver"
      - "traefik.http.routers.repo.service=repo"
      - "traefik.http.services.repo.loadBalancer.server.port=8081"