---
service_dir: "{{ project_dir }}/nexus"

# nexus image tag
nexus_image_tag: 3.77.1

# minio domain
nexus_main_domain: "repo.{{ main_domain }}"
nexus_main_url: "https://{{ nexus_main_domain }}"

delete_repository:
  - maven-snapshots
  - maven-public
  - maven-central
  - nuget-hosted
  - maven-releases
  - nuget-group
  - nuget.org-proxy

create_blob:
  - apt
  - docker
  - raw

anonymous_config:
  enabled: true
  userId: anonymous
  realmName: NexusAuthorizingRealm

role:
  id: repo_admin
  name: repo_admin
  description: repository admin
  privileges: nx-repository-admin-*-*-*
  roles: nx-anonymous

user:
  id: repo
  first_name: repo
  last_name: repo
  email_address: repo@RahBia.ir
  status: active
  roles_name: repo_admin

create_apt_repository:
  - name: "ubuntu"
    remote_url: "http://archive.ubuntu.com/ubuntu"
    distribution: "jammy,jammy-updates,jammy-backports,focal"
    blob: "apt"
    cleanup_policy: "docker"

  - name: "ubuntu-docker"
    remote_url: "https://download.docker.com/linux/ubuntu"
    distribution: "jammy"
    blob: "apt"
    cleanup_policy: "docker"

  - name: "ubuntu-security"
    remote_url: "http://security.ubuntu.com/ubuntu"
    distribution: "jammy-security"
    blob: "apt"
    cleanup_policy: "docker"

  - name: "debian-docker"
    remote_url: "https://download.docker.com/linux/debian/"
    distribution: "bookworm"
    blob: "apt"
    cleanup_policy: "docker"

  - name: "debian-security"
    remote_url: "https://security.debian.org"
    distribution: "bookworm-security"
    blob: "apt"
    cleanup_policy: "docker"

  - name: "debian"
    remote_url: "https://deb.debian.org/debian"
    distribution: "bookworm,bookworm-backports,bookworm-updates"
    blob: "apt"
    cleanup_policy: "docker"

create_docker_repository:
  - name: "hub"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://hub.hamdocker.ir"
    repo_port: "9091"
    index_type: "HUB"
    repo_domain: "hub.{{ main_domain }}"

  - name: "quay"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://quay.io"
    repo_port: "9092"
    index_type: "REGISTRY"
    repo_domain: "quay.{{ main_domain }}"

  - name: "k8s"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://registry.k8s.io"
    repo_port: "9093"
    index_type: "REGISTRY"
    repo_domain: "k8s.{{ main_domain }}"

  - name: "gcr"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://gcr.io"
    repo_port: "9094"
    index_type: "REGISTRY"
    repo_domain: "gcr.{{ main_domain }}"

  - name: "k8s-gcr"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://k8s.gcr.io"
    repo_port: "9095"
    index_type: "REGISTRY"
    repo_domain: "k8s-gcr.{{ main_domain }}"

  - name: "github"
    blob: "docker"
    cleanup_policy: "docker"
    remote_url: "https://ghcr.io"
    repo_port: "9096"
    index_type: "REGISTRY"
    repo_domain: "github.{{ main_domain }}"

create_raw_repository:
  - name: "kube"
    blob: "raw"
    cleanup_policy: "raw"
    remote_url: "https://files.m.daocloud.io"
    content_disposition: "INLINE"

create_pypi_repository:
  - name: "pypi"
    blob: "raw"
    cleanup_policy: "pypi"
    remote_url: "https://pypi.org/"