---
- name: Check if the repository exists
  uri:
    url: "{{ nexus_main_url }}/service/rest/v1/repositories/{{ item }}"
    method: GET
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 200
  register: repo_check_response
  failed_when: repo_check_response.status != 200
  ignore_errors: true
  tags:
    - setup_nexus
    - config_nexus
    - create_apt_repo

- name: Create APT proxy repositories
  uri:
    url: "{{ nexus_main_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: >-
      {
        "name": "{{ item.name }}",
        "online": true,
        "recipe": "apt-proxy",
        "attributes": {
          "httpclient": {
            "blocked": false,
            "autoBlock": true
          },
          "storage": {
            "blobStoreName": "{{ item.blob }}",
            "strictContentTypeValidation": true
          },
          "proxy": {
            "remoteUrl": "{{ item.remote_url }}",
            "contentMaxAge": 1440,
            "metadataMaxAge": 1440
          },
          "apt": {
            "distribution": "{{ item.distribution }}",
            "flat": false
          }
        }
      }
    status_code: 201
  when: repo_check_response.status == 200
  tags:
    - setup_nexus
    - config_nexus
    - create_apt_repo
