---
- name: Prune all unused resource in docker daemon
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    builder_cache: true